" no vi compatibility
set nocompatible
syntax on
set nojoinspaces

" Other good ones: IDLE, hybrid, habiLight, darkrobot, northland,
" solarized, peachpuff, desert, zellner, distinguished
colorscheme hybrid
"set background=dark

"TODO: activate this only in .tex files.
"hi clear SpellBad
"hi SpellBad ctermfg=red

nmap ; :
vmap ; :

"See <https://www.reddit.com/r/vim/comments/3hwall/how_to_close_vim_when_last_buffer_is_deleted/>.
function CloseBuffer()
	let cnt = 0
	for i in range(0, bufnr("$"))
		if buflisted(i)
			let cnt += 1
		endif
	endfor
	if cnt > 1
		bdelete
	else
		quit
	endif
endfunction

nnoremap <C-D> :call CloseBuffer()<CR>
nnoremap <C-S> :write<CR>

"Assume *.tex files are LaTeX.
let g:tex_flavor = "latex"

let g:vimwiki_list = [{'path':'~/Documents/Personal/Wiki', 'path_html':'~/Documents/Personal/WikiHTML'}]

set nohlsearch
set display=lastline
set number
set numberwidth=1
" Working off of <http://peox.net/articles/vimconfig.html>.
" NERDCommenter complains if filetype plugins are off.
filetype plugin on
" Exceptions (in particular TeX) are handled in filetype.vim.
filetype indent on

set runtimepath+=$HOME/.vim/colors

set autochdir
set autoread " watch for file changes by other applications

"When the statusline is on top, you can't see the tabline.
"let g:airline_statusline_ontop = 1
let g:airline#extensions#tabline#enabled = 1

"TODO: Possibly use instead <C-H> (remap) and <C-L>.
map <C-Tab> :bnext<CR>
map <C-S-Tab> :bprevious<CR>
"Hide (instead of unloading) buffers when changing from them.
set hidden

autocmd BufNewFile,BufRead /home/brown/Documents/Research/Hierarchical_Storage/*.{py,pyx} setlocal path+=~brown/HS/packages/multilevel,~brown/HS/packages/helpers
autocmd BufNewFile,BufRead /home/brown/Documents/Research/Hierarchical_Storage/*.{py,pyx} setlocal tags+=~brown/HS/tags
autocmd BufNewFile,BufRead /home/brown/Documents/Research/Hierarchical_Storage/papers/tensored-nd-sobolev*.tex setlocal path+=~brown/HS/papers/tensored-nd-sobolev
autocmd BufNewFile,BufRead /home/brown/Documents/Research/Hierarchical_Storage/papers/*.tex setlocal path+=~brown/HS/
autocmd BufNewFile,BufRead /home/brown/Documents/Research/Hierarchical_Storage/papers/tensored-nd-sobolev*.tex setlocal path+=~brown/HS/papers/tensored-nd-sobolev
autocmd BufNewFile,BufRead /home/brown/Documents/Research/Hierarchical_Storage/papers/unstructured*.tex setlocal path+=~brown/HS/papers/unstructured
autocmd BufNewFile,BufRead /home/brown/Documents/Research/thesis/*.tex setlocal path+=~brown/thesis,~brown/thesis/texmf/tex/latex
