#!/bin/sh

PAPERDIR="${HOME}/papers"
UUIDDB="${XDG_DATA_HOME:-${HOME}/.local/share/}/toread/uuids.csv"
if [ ! -f "${UUIDDB}" ]
then
	echo "UUID database not found (expected at '${UUIDDB}'). Exiting."
	exit 1
fi

if [ $# -ne 1 ]
then
	echo 'Usage: read [BibTeX key]'
	echo 'Possible keys:'
	#TODO: try printing these with spaces instead of newlines.
	awk -F ',' '{print $1}' < "${UUIDDB}"
	exit 1
fi

KEY=$1
UUID=$(awk -F ',' '$1 == "'${KEY}'" {print $2; exit}' < "${UUIDDB}")

if [ ! "${UUID}" ]
then
	echo "No task associated to that key found. Exiting."
	exit 1
fi

PAPERPDF="${PAPERDIR}/${KEY}/${KEY}.pdf"
if [ ! -f "${PAPERPDF}" ]
then
	echo "Paper not found (expected at '${PAPERPDF}'). Exiting."
	exit 1
fi

#TODO: check whether you've started the task or not. If not, open PDF and mark as started. If started, mark as done.
xdg-open "${PAPERPDF}" &
task "${UUID}" start
